In [ ]:
from os.path import basename, exists


def download(url):
    filename = basename(url)
    if not exists(filename):
        from urllib.request import urlretrieve

        local, _ = urlretrieve(url, filename)
        print("Downloaded " + local)


download("https://github.com/AllenDowney/ThinkStats/raw/v3/nb/thinkstats.py")

In [2]:
try:
    import empiricaldist
except ImportError:
    %pip install empiricaldist

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from thinkstats import decorate

In [5]:
from empiricaldist import FreqTab
ftab = FreqTab.from_seq([1,2,2,3,5])
ftab

1    1
2    2
3    1
5    1
Name: , dtype: int64

In [7]:
n = ftab.sum()
n

np.int64(5)

In [9]:
pmf = ftab/n
pmf

1    0.2
2    0.4
3    0.2
5    0.2
Name: , dtype: float64